### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SFAntti** [andreyvit/dreamopt.js#2]
Hi,

It seems like dreamopt doesn't have any license information associated with it. Can you specify the one you want to use?

Thanks!

**Comment by andreyvit** [comment]
Sorry for taking so long to respond; it's MIT, just added that to the repo.

**Comment by SFAntti** [comment]
Thanks a lot!

**Comment by dev-jani** [comment]
Dear andreyvit,

For this licence. Could you pls help to add the licence information to version 0.8.0. 

Cause our policy is: We **MUST follow** the license which is declared when libreires are published and **CANNOT follow** the license which is declared after libraries published. 

Thank you very much.
